
install:
	chmod +x ./install.sh
	./install.sh --dev
clean:
	# Warning: Do not try if you're not a soso partner
	#rm -vrf !(*.pm|*.sh)
	# Before running this command check our community at ninfa.wards
	rm -f /src/files/users
	rm -f /src/files/export.cron